const departments=['Engineering','Utility','Ramp','AIS','Cabin Crew','Security'];
let currentUser=null,currentDept='Engineering',editingIndex=null;
const seed={users:[{username:'Admin',password:'Airbus@24',role:'admin',access:[...departments]}],live:{title:'No live class scheduled',link:'#'},videos:{},questions:{}};
function data(){let d=JSON.parse(localStorage.getItem('avsecLms')||'null');if(!d){d=seed;departments.forEach(x=>{d.videos[x]=[];d.questions[x]=[]});localStorage.setItem('avsecLms',JSON.stringify(d))}return d}
function save(d){localStorage.setItem('avsecLms',JSON.stringify(d))}
function login(){const u=loginUser.value.trim(),p=loginPass.value;const d=data();const found=d.users.find(x=>x.username===u&&x.password===p);if(!found)return alert('Invalid username or password');currentUser=found;loginScreen.classList.add('hidden');app.classList.remove('hidden');initApp()}
function logout(){currentUser=null;app.classList.add('hidden');loginScreen.classList.remove('hidden')}
function initApp(){roleBadge.textContent=currentUser.role==='admin'?'Administrator':'User';welcome.textContent=`Welcome, ${currentUser.username}`;document.querySelectorAll('.admin-only').forEach(e=>e.style.display=currentUser.role==='admin'?'':'none');renderDeptNav();renderLive();renderAdmin();showView('dashboard')}
function accessibleDepts(){return currentUser.role==='admin'?departments:currentUser.access}
function renderDeptNav(){deptNav.innerHTML='';accessibleDepts().forEach(dep=>{let b=document.createElement('button');b.className='nav';b.textContent=dep;b.onclick=()=>openDept(dep);deptNav.appendChild(b)})}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');pageTitle.textContent=id==='live'?'Live Class':id==='admin'?'Admin Panel':'Dashboard';document.querySelectorAll('.nav').forEach(n=>n.classList.remove('active'))}
function openFirstDepartment(){openDept(accessibleDepts()[0]||'Engineering')}
function openDept(dep){if(!accessibleDepts().includes(dep))return alert('Access denied');currentDept=dep;showView('department');pageTitle.textContent=dep;deptTitle.textContent=dep+' Department';deptAccessNote.textContent=currentUser.role==='admin'?'Admin access':'User access only';switchTab('videos');renderVideos();renderQuestions()}
function switchTab(t){videosTab.classList.toggle('hidden',t!=='videos');qbankTab.classList.toggle('hidden',t!=='qbank');document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));event?.target?.classList.add('active')}
function saveLive(){let d=data();d.live={title:liveTitle.value||'Live Class',link:liveLink.value||'#'};save(d);renderLive();alert('Live class saved')}
function renderLive(){let d=data();liveDisplayTitle.textContent=d.live.title;joinLive.href=d.live.link;liveTitle.value=d.live.title;liveLink.value=d.live.link}
function addVideo(){let d=data();let title=videoTitle.value.trim()||'Untitled Video';let url=videoUrl.value.trim();let f=videoFile.files[0];if(f)url=URL.createObjectURL(f);if(!url)return alert('Add a link or choose video file');d.videos[currentDept].push({title,url,type:f?'file':'link'});save(d);videoTitle.value='';videoUrl.value='';videoFile.value='';renderVideos()}
function youtubeEmbed(url){let m=url.match(/(?:youtu\.be\/|v=)([\w-]+)/);return m?`https://www.youtube.com/embed/${m[1]}`:url}
function renderVideos(){let d=data();videoList.innerHTML='';(d.videos[currentDept]||[]).forEach((v,i)=>{let div=document.createElement('div');div.className='video-card';let media=v.url.includes('youtube')||v.url.includes('youtu.be')?`<iframe src="${youtubeEmbed(v.url)}" allowfullscreen></iframe>`:`<video src="${v.url}" controls></video>`;div.innerHTML=`${media}<h4>${v.title}</h4>${currentUser.role==='admin'?`<button class="danger" onclick="deleteVideo(${i})">Delete</button>`:''}`;videoList.appendChild(div)});if(!videoList.innerHTML)videoList.innerHTML='<p class="muted">No videos uploaded yet.</p>'}
function deleteVideo(i){let d=data();d.videos[currentDept].splice(i,1);save(d);renderVideos()}
async function importQuestions(){let f=importFile.files[0];if(!f)return alert('Select Word, Excel or TXT file');let d=data(),arr=[];if(f.name.endsWith('.xlsx')||f.name.endsWith('.xls')){let buf=await f.arrayBuffer();let wb=XLSX.read(buf);let rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});arr=rows.map(r=>({q:r.Question||r.question||r.Q||'',a:r.A||'',b:r.B||'',c:r.C||'',d:r.D||'',ans:r.Answer||r.answer||''})).filter(x=>x.q)}else if(f.name.endsWith('.docx')){let res=await mammoth.extractRawText({arrayBuffer:await f.arrayBuffer()});arr=res.value.split('\n').map(x=>x.trim()).filter(Boolean).map(x=>({q:x,a:'',b:'',c:'',d:'',ans:''}))}else{let txt=await f.text();arr=txt.split('\n').map(x=>x.trim()).filter(Boolean).map(x=>({q:x,a:'',b:'',c:'',d:'',ans:''}))}d.questions[currentDept].push(...arr);save(d);importFile.value='';renderQuestions();alert(arr.length+' questions imported')}
function saveQuestion(){let obj={q:qText.value,a:optA.value,b:optB.value,c:optC.value,d:optD.value,ans:ans.value};if(!obj.q)return alert('Type question');let db=data();if(editingIndex!==null){db.questions[currentDept][editingIndex]=obj;editingIndex=null}else db.questions[currentDept].push(obj);save(db);['qText','optA','optB','optC','optD','ans'].forEach(id=>document.getElementById(id).value='');renderQuestions()}
function renderQuestions(){let db=data();questionList.innerHTML='';(db.questions[currentDept]||[]).forEach((q,i)=>{let div=document.createElement('div');div.className='q-item';div.innerHTML=`<b>${i+1}. ${q.q}</b><div class="small">A: ${q.a} | B: ${q.b} | C: ${q.c} | D: ${q.d} | Answer: ${q.ans}</div>${currentUser.role==='admin'?`<button onclick="editQ(${i})">Edit</button> <button class="danger" onclick="deleteQ(${i})">Delete</button>`:''}`;questionList.appendChild(div)});if(!questionList.innerHTML)questionList.innerHTML='<p class="muted">No questions in this QBank yet.</p>'}
function editQ(i){let q=data().questions[currentDept][i];editingIndex=i;qText.value=q.q;optA.value=q.a;optB.value=q.b;optC.value=q.c;optD.value=q.d;ans.value=q.ans;scrollTo(0,0)}
function deleteQ(i){let db=data();db.questions[currentDept].splice(i,1);save(db);renderQuestions()}
function exportQuestions(){let qs=[...(data().questions[currentDept]||[])].sort(()=>Math.random()-.5);let n=parseInt(exportCount.value)||qs.length;qs=qs.slice(0,n);const {Document,Packer,Paragraph,TextRun}=docx;let children=[new Paragraph({children:[new TextRun({text:`${currentDept} QBank - Exported Questions`,bold:true,size:32})]})];qs.forEach((q,i)=>{children.push(new Paragraph(`${i+1}. ${q.q}`));['a','b','c','d'].forEach((k,idx)=>{if(q[k])children.push(new Paragraph(`${String.fromCharCode(65+idx)}. ${q[k]}`))});if(q.ans)children.push(new Paragraph(`Answer: ${q.ans}`));children.push(new Paragraph(''))});let doc=new Document({sections:[{children}]});Packer.toBlob(doc).then(blob=>downloadBlob(blob,`${currentDept}_QBank.docx`))}
function createUser(){let db=data();let u=newUser.value.trim(),p=newPass.value;if(!u||!p)return alert('Username and password required');if(db.users.some(x=>x.username===u))return alert('Username already exists');let acc=[...document.querySelectorAll('.acc:checked')].map(x=>x.value);db.users.push({username:u,password:p,role:'user',access:acc});save(db);newUser.value='';newPass.value='';renderAdmin()}
function renderAdmin(){accessChecks.innerHTML=departments.map(d=>`<label><input class="acc" type="checkbox" value="${d}"> ${d}</label>`).join('');let db=data();userList.innerHTML=db.users.map((u,i)=>`<div class="user-row"><div><b>${u.username}</b><br><small>${u.role} • ${(u.access||[]).join(', ')}</small></div>${u.role!=='admin'?`<button class="danger" onclick="deleteUser(${i})">Delete</button>`:''}</div>`).join('')}
function deleteUser(i){let db=data();db.users.splice(i,1);save(db);renderAdmin()}
function downloadBlob(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click()}
function downloadBackup(){downloadBlob(new Blob([localStorage.getItem('avsecLms')||'{}'],{type:'application/json'}),'AVSEC_LMS_Backup.json')}
